import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Activity, Archive, Check, ClipboardCheck, Clock3, FolderPlus, Loader2, Settings2, ShieldCheck, Users } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Shell } from "./Home";

function formatDate(value: Date | string) { return new Date(value).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }); }
function statusTone(status: string) { return status === "approved" || status === "completed" ? "text-emerald-300" : status === "changes_requested" || status === "failed" ? "text-orange-300" : "text-accent"; }

export default function Operations() {
  useAuth({ redirectOnUnauthenticated: true });
  const utils = trpc.useUtils();
  const workspaceQuery = trpc.workspace.overview.useQuery();
  const [projectId, setProjectId] = useState<number | null>(null);
  const activeProject = useMemo(() => workspaceQuery.data?.projects.find(project => project.id === projectId) ?? workspaceQuery.data?.projects[0], [workspaceQuery.data, projectId]);
  const selectedId = activeProject?.id ?? 0;
  const summary = trpc.governance.summary.useQuery({ projectId: selectedId }, { enabled: Boolean(selectedId) });
  const jobs = trpc.jobs.list.useQuery({ projectId: selectedId }, { enabled: Boolean(selectedId) });
  const reviews = trpc.reviews.list.useQuery({ projectId: selectedId }, { enabled: Boolean(selectedId) });
  const [newProjectName, setNewProjectName] = useState("");
  const [retentionDays, setRetentionDays] = useState("30");
  const [monthlyQuota, setMonthlyQuota] = useState("25");
  const [reviewRunId, setReviewRunId] = useState("");
  const [reviewNote, setReviewNote] = useState("");
  const refresh = async () => { await Promise.all([utils.workspace.overview.invalidate(), utils.governance.summary.invalidate(), utils.jobs.list.invalidate(), utils.reviews.list.invalidate(), utils.runs.list.invalidate()]); };
  const createProject = trpc.workspace.createProject.useMutation({ onSuccess: async data => { toast.success("Project created with an owner-only membership"); setNewProjectName(""); setProjectId(data.id ?? null); await refresh(); }, onError: error => toast.error(error.message) });
  const updateSettings = trpc.projects.settings.useMutation({ onSuccess: async () => { toast.success("Project retention and quota policy saved"); await refresh(); }, onError: error => toast.error(error.message) });
  const cleanup = trpc.governance.cleanup.useMutation({ onSuccess: async data => { toast.success(`${data.removed} expired run${data.removed === 1 ? "" : "s"} removed`); await refresh(); }, onError: error => toast.error(error.message) });
  const decide = trpc.reviews.decide.useMutation({ onSuccess: async () => { toast.success("Review decision recorded in the audit trail"); setReviewNote(""); await refresh(); }, onError: error => toast.error(error.message) });

  if (workspaceQuery.isLoading) return <div className="grid min-h-screen place-items-center bg-background"><Loader2 className="animate-spin text-accent" /></div>;
  if (!activeProject) return <div className="grid min-h-screen place-items-center bg-background p-6"><div className="panel max-w-lg"><div className="font-display text-2xl font-semibold">No accessible project</div><p className="mt-2 text-sm text-muted-foreground">Reload to bootstrap a private workspace and its default project.</p><Button className="mt-4" onClick={() => workspaceQuery.refetch()}>Reload workspace</Button></div></div>;

  const currentRetention = String(activeProject.retentionDays);
  const currentQuota = String(activeProject.monthlyRunQuota);
  return <Shell onNewRun={() => toast.info("Open Overview to start a new verification run in the selected project.")} onConfig={() => toast.info("Open Overview to edit the selected project rubric.")}>
    <div className="page-wrap">
      <section className="hero-row">
        <div><div className="eyebrow text-accent">TEAM READINESS · NO NEW SERVICE COST</div><h1 className="font-display mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">Govern project quality without an always-on worker.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-muted-foreground">Every action is scoped to a workspace and project, stored in the existing database, and initiated by a signed-in user. No new API key, polling process, or background runtime is required.</p></div>
        <div className="panel w-full max-w-sm"><div className="eyebrow text-muted-foreground">ACTIVE PROJECT</div><select aria-label="Active project" className="mt-3 w-full rounded-xl border border-border bg-muted/30 px-3 py-2 text-sm" value={activeProject.id} onChange={event => setProjectId(Number(event.target.value))}>{workspaceQuery.data?.projects.map(project => <option key={project.id} value={project.id}>{project.name} · {project.role}</option>)}</select><div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={14} className="text-accent" />Role: {activeProject.role}</div></div>
      </section>

      <section className="metric-grid">
        <div className="metric-card"><div className="metric-label">Monthly runs</div><div className="metric-value">{summary.data?.quota?.verificationRuns ?? 0}<span className="metric-unit">/{summary.data?.quota?.project.monthlyRunQuota ?? activeProject.monthlyRunQuota}</span></div><div className="metric-foot"><Activity size={14} />{summary.data?.quota?.remainingRuns ?? activeProject.monthlyRunQuota} user-triggered runs remaining</div></div>
        <div className="metric-card"><div className="metric-label">Retention window</div><div className="metric-value">{activeProject.retentionDays}<span className="metric-unit">d</span></div><div className="metric-foot"><Archive size={14} />{summary.data?.eligibleForCleanup ?? 0} run(s) eligible now</div></div>
        <div className="metric-card"><div className="metric-label">Review records</div><div className="metric-value">{reviews.data?.length ?? 0}</div><div className="metric-foot"><ClipboardCheck size={14} />Decisions are retained in audit history</div></div>
      </section>

      <section className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]">
        <div className="panel"><div className="panel-head"><div><div className="eyebrow text-accent">PROJECTS & ACCESS</div><h2 className="font-display mt-2 text-xl font-semibold">Isolated workspaces and roles</h2></div><Users className="text-accent" size={20} /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Owners and admins manage project policies; reviewers can record quality decisions; members can run the project’s configured quality gate. The current member list uses real authenticated users only.</p><div className="mt-5 rounded-2xl border border-border bg-muted/20 p-4"><div className="flex items-center justify-between"><div><div className="font-medium">{summary.data?.members.length ?? 0} direct project member(s)</div><div className="mt-1 text-xs text-muted-foreground">Workspace-level owners and admins inherit access.</div></div><ShieldCheck size={20} className="text-accent" /></div><div className="mt-4 flex flex-wrap gap-2">{summary.data?.members.map(row => <span key={row.membership.id} className="rounded-full border border-border px-3 py-1.5 text-xs"><strong>{row.user.name || row.user.email || `User ${row.user.id}`}</strong> · {row.membership.role}</span>)}</div></div><div className="mt-5 grid gap-2 sm:grid-cols-[1fr_auto]"><Input value={newProjectName} onChange={event => setNewProjectName(event.target.value)} placeholder="New project name" /><Button disabled={!newProjectName.trim() || createProject.isPending} onClick={() => createProject.mutate({ name: newProjectName.trim(), retentionDays: 30, monthlyRunQuota: 25 })}>{createProject.isPending ? <Loader2 className="animate-spin" /> : <FolderPlus size={15} />}Create project</Button></div></div>
        <div className="panel"><div className="panel-head"><div><div className="eyebrow text-accent">POLICY CONTROLS</div><h2 className="font-display mt-2 text-xl font-semibold">Quota and retention</h2></div><Settings2 className="text-accent" size={20} /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Limits are stored per project and checked before new runs begin. Retention cleanup is a deliberate, audited action rather than an unattended background task.</p><div className="mt-5 grid grid-cols-2 gap-3"><div><label className="field-label">Retention days</label><Input type="number" min="1" max="365" value={retentionDays || currentRetention} onChange={event => setRetentionDays(event.target.value)} /></div><div><label className="field-label">Monthly run quota</label><Input type="number" min="1" max="500" value={monthlyQuota || currentQuota} onChange={event => setMonthlyQuota(event.target.value)} /></div></div><Button className="mt-4 w-full" variant="outline" disabled={updateSettings.isPending} onClick={() => updateSettings.mutate({ projectId: activeProject.id, retentionDays: Number(retentionDays || currentRetention), monthlyRunQuota: Number(monthlyQuota || currentQuota) })}>Save policy</Button><Button className="mt-2 w-full" variant="destructive" disabled={cleanup.isPending || !(summary.data?.eligibleForCleanup ?? 0)} onClick={() => { if (window.confirm(`Remove ${summary.data?.eligibleForCleanup ?? 0} expired run(s)? This cannot be undone.`)) cleanup.mutate({ projectId: activeProject.id, confirm: true }); }}>{cleanup.isPending ? <Loader2 className="animate-spin" /> : <Archive size={15} />}Run manual retention cleanup</Button></div>
      </section>

      <section className="grid gap-4 xl:grid-cols-2">
        <div className="panel"><div className="panel-head"><div><div className="eyebrow text-accent">USER-TRIGGERED JOBS</div><h2 className="font-display mt-2 text-xl font-semibold">Execution history</h2></div><Clock3 className="text-accent" size={20} /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Jobs record progress and outcomes, but no worker persists after the initiating request completes. Verification remains available from the overview screen.</p><div className="mt-5 space-y-2">{jobs.data?.length ? jobs.data.map(job => <div key={job.id} className="flex items-center justify-between gap-4 rounded-xl border border-border/70 bg-muted/20 p-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{job.type === "verification" ? "Verification run" : "Retention cleanup"}</div><div className="mt-1 text-xs text-muted-foreground">Job #{job.id} · {formatDate(job.createdAt)}</div></div><div className={`text-right text-xs font-semibold uppercase tracking-wider ${statusTone(job.status)}`}>{job.status}<div className="mt-1 font-normal normal-case text-muted-foreground">{job.progressPercent}%</div></div></div>) : <div className="rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">No project jobs yet.</div>}</div></div>
        <div className="panel"><div className="panel-head"><div><div className="eyebrow text-accent">REVIEW STATES</div><h2 className="font-display mt-2 text-xl font-semibold">Human quality decisions</h2></div><ClipboardCheck className="text-accent" size={20} /></div><p className="mt-3 text-sm leading-6 text-muted-foreground">A reviewer can approve a run or request changes. Decisions include an optional note and are included in the audit trail.</p><div className="mt-5 grid gap-2 sm:grid-cols-[.6fr_1fr]"><Input type="number" min="1" value={reviewRunId} onChange={event => setReviewRunId(event.target.value)} placeholder="Run ID" /><Input value={reviewNote} onChange={event => setReviewNote(event.target.value)} placeholder="Decision note (optional)" /></div><div className="mt-2 grid grid-cols-2 gap-2"><Button variant="outline" disabled={!reviewRunId || decide.isPending} onClick={() => decide.mutate({ runId: Number(reviewRunId), status: "changes_requested", note: reviewNote || undefined })}>Request changes</Button><Button disabled={!reviewRunId || decide.isPending} onClick={() => decide.mutate({ runId: Number(reviewRunId), status: "approved", note: reviewNote || undefined })}><Check size={15} />Approve run</Button></div><div className="mt-5 space-y-2">{reviews.data?.length ? reviews.data.slice(0, 6).map(review => <div key={review.id} className="rounded-xl border border-border/70 bg-muted/20 p-3"><div className="flex items-center justify-between"><span className="text-sm font-medium">Run #{review.runId}</span><span className={`text-xs font-semibold uppercase tracking-wider ${statusTone(review.status)}`}>{review.status.replace("_", " ")}</span></div>{review.note ? <div className="mt-1 text-xs text-muted-foreground">{review.note}</div> : null}</div>) : <div className="rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">Record a decision after a verification run is available.</div>}</div></div>
      </section>

      <section className="panel"><div className="panel-head"><div><div className="eyebrow text-accent">AUDIT LOG</div><h2 className="font-display mt-2 text-xl font-semibold">Project accountability</h2></div><ShieldCheck className="text-accent" size={20} /></div><div className="mt-5 space-y-2">{summary.data?.audits.length ? summary.data.audits.map(row => <div key={row.event.id} className="grid gap-2 rounded-xl border border-border/70 bg-muted/20 p-3 sm:grid-cols-[auto_1fr_auto]"><div className="grid size-8 place-items-center rounded-lg bg-accent/10 text-accent"><Activity size={15} /></div><div><div className="text-sm font-medium">{row.event.action}</div><div className="mt-1 text-xs text-muted-foreground">{row.actor.name || row.actor.email || `User ${row.actor.id}`} · {row.event.resourceType}{row.event.resourceId ? ` #${row.event.resourceId}` : ""}</div></div><div className="text-xs text-muted-foreground">{formatDate(row.event.createdAt)}</div></div>) : <div className="rounded-xl border border-dashed border-border p-5 text-sm text-muted-foreground">The first project action will create an audit event.</div>}</div></section>
    </div>
  </Shell>;
}
